### ISSUE TITLE
Add WaterTAP As Required Dependency for PrOMMiS

### ISSUE THREAD

**Issue by bpaul4** [prommis/prommis#25]
Going forwards, a good amount of process modeling and cost estimation work will leverage WaterTAP and we should consider how to integrate the package to work with the PrOMMiS code.

Specifically, proposed models and tests introduced in #22 and #23 require WaterTAP as part of the CI suite.

**Comment by lbianchi-lbl** [comment]
- There might be some complications if there are conflicts between the `idaes-pse` requirements between WaterTAP and this repository
- My plan would be to open a separate PR to add WaterTAP as a (dev-only? optional?) requirement, and then merge the changes back into #22 and #23

**Comment by dangunter** [comment]
I also need this for the UI work since the Python UI export code is (at least for now) in the main watertap repo.

**Comment by bpaul4** [comment]
Completed via #27.
