### ISSUE TITLE
Codecov upload failures

### ISSUE THREAD

**Issue by lbianchi-lbl** [prommis/prommis#63]
## Problem

- Codecov uploads have been failing, causing the CI job where the report is generated and uploaded to fail as well
  ![image](https://github.com/prommis/prommis/assets/48035537/f42d8780-f8ba-4cb2-ac9b-62144240388a)

## Solution

- [x] Short/medium-term: move the Codecov upload step to a separate dependent job so when it fails it can be restarted without having to re-run the test suite
- [ ] Long-term: move the Codecov upload step to a separate dependent _workflow_ that is able to access repository secrets so that a dedicated Codecov auth token can be used (as opposed to relying on the GHA "no tokens needed" default we have now, which is likely what's being causing the failures)

**Comment by ksbeattie** [comment]
We've done as much as we can here, without more response from CodeCov.
