### ISSUE TITLE
Initializer for Solvent Extraction

### ISSUE THREAD

**Issue by MarcusHolly** [prommis/prommis#81]
While the `BlockTriangularizationInitializer` is able to initialize the SX unit model in the simple case of https://github.com/prommis/prommis/blob/main/src/prommis/solvent_extraction/sx_model_flowsheet_steady_state.py, it fails to do so in more complex scenarios like https://github.com/prommis/prommis/pull/47#discussion_r1633436319

In short, there is a need for a custom `SXinitializer`. There are plenty examples in the IDAES [unit model](https://github.com/IDAES/idaes-pse/tree/main/idaes/models/unit_models) files.

**Comment by ArkoprabhoDasgupta** [comment]
Please check PR #85 , I have added the initializer there
